/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Процесс жив. Не проверяет зависимости — для этого /ready.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Готовность обслуживать запросы: база доступна.
         *
         *     Отделено от /health намеренно. Балансировщик снимает трафик по
         *     /ready, но не перезапускает процесс — перезапуск при недоступной
         *     базе не помогает и только удлиняет простой.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/ca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ca Certificate
         * @description Сертификат удостоверяющего центра. Без аутентификации — он публичен по определению.
         */
        get: operations["get_ca_certificate_gateway_v1_ca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll */
        post: operations["enroll_gateway_v1_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Проверка аутентификации по клиентскому сертификату.
         */
        get: operations["whoami_gateway_v1_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew */
        post: operations["renew_gateway_v1_renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Config */
        get: operations["get_agent_config_gateway_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_gateway_v1_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/v1/commands/{command_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Command Result */
        post: operations["submit_command_result_gateway_v1_commands__command_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Действующие входы оператора: где именно открыта консоль от его имени.
         */
        get: operations["list_sessions_api_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Own Session */
        delete: operations["revoke_own_session_api_v1_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tokens */
        get: operations["list_tokens_api_v1_enrollment_tokens_get"];
        put?: never;
        /** Create Token */
        post: operations["create_token_api_v1_enrollment_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollment-tokens/{token_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Token */
        post: operations["revoke_token_api_v1_enrollment_tokens__token_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Agent */
        get: operations["read_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_api_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Certificates */
        get: operations["list_agent_certificates_api_v1_agents__agent_id__certificates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Agent
         * @description Отзывает все действующие сертификаты агента и снимает его с обслуживания.
         *
         *     Отзыв доступен только администратору: это действие мгновенно выводит
         *     хост из-под наблюдения, и оно же — способ скрыть следы.
         */
        post: operations["revoke_agent_api_v1_agents__agent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Global Config */
        get: operations["read_global_config_api_v1_config_get"];
        /** Replace Global Config */
        put: operations["replace_global_config_api_v1_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Group Config */
        get: operations["read_group_config_api_v1_groups__group_id__config_get"];
        /** Replace Group Config */
        put: operations["replace_group_config_api_v1_groups__group_id__config_put"];
        post?: never;
        /** Delete Group Config */
        delete: operations["delete_group_config_api_v1_groups__group_id__config_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Effective Agent Config */
        get: operations["read_effective_agent_config_api_v1_agents__agent_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commands */
        get: operations["list_commands_api_v1_agents__agent_id__commands_get"];
        put?: never;
        /** Create Command */
        post: operations["create_command_api_v1_agents__agent_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_v1_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_v1_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Update Group */
        patch: operations["update_group_api_v1_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create Console User */
        post: operations["create_console_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Console User */
        patch: operations["update_console_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Api Key
         * @description Выдаёт ключ для автоматизации. Прежний ключ учётной записи перестаёт работать.
         */
        post: operations["issue_api_key_api_v1_users__user_id__api_key_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Overview
         * @description Одним запросом всё, что показывает дашборд.
         *
         *     Именно одним: шесть отдельных запросов из браузера дали бы шесть
         *     проверок сессии и шесть обходов дерева групп ради одной страницы.
         */
        get: operations["read_overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fleet Commands */
        get: operations["list_fleet_commands_api_v1_commands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Audit
         * @description Журнал действий операторов, от новых к старым.
         *
         *     Администратор видит весь журнал, оператор — только свои записи:
         *     читать, кто именно из коллег открывал чей перехват, — это надзорное
         *     право, а не рядовое.
         */
        get: operations["read_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Audit */
        get: operations["verify_audit_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Audit Entry */
        get: operations["read_audit_entry_api_v1_audit__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentConfigDocument
         * @description Полная форма конфигурации агента.
         *
         *     extra="forbid" на каждом уровне обязателен: опечатка вроде
         *     heartbeat_intervall иначе молча не применится, и разбор такого
         *     инцидента занимает часы.
         */
        AgentConfigDocument: {
            /**
             * @default {
             *       "heartbeat_interval_seconds": 30,
             *       "event_batch_max": 500,
             *       "event_batch_max_bytes": 4194304,
             *       "backoff_base_seconds": 1,
             *       "backoff_max_seconds": 300
             *     }
             */
            transport: components["schemas"]["TransportConfig"];
            /**
             * @default {
             *       "max_bytes": 524288000,
             *       "max_age_days": 7
             *     }
             */
            buffer: components["schemas"]["BufferConfig"];
            /**
             * @default {
             *       "level": "info"
             *     }
             */
            logging: components["schemas"]["LoggingConfig"];
            /** Policies */
            policies?: {
                [key: string]: unknown;
            };
        };
        /** AgentConfigResponse */
        AgentConfigResponse: {
            /** Version */
            version: number;
            /** Document */
            document: {
                [key: string]: unknown;
            };
        };
        /** AgentDetail */
        AgentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Hostname */
            hostname: string;
            /** Os */
            os: string;
            /** Os Version */
            os_version: string;
            /** Arch */
            arch: string;
            /** Agent Version */
            agent_version: string;
            /** Status */
            status: string;
            /** Group Id */
            group_id: string | null;
            /** Group Name */
            group_name: string | null;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Last Ip */
            last_ip: string | null;
            /** Clock Skew Ms */
            clock_skew_ms: number;
            /** Config Version */
            config_version: number;
            /**
             * Enrolled At
             * Format: date-time
             */
            enrolled_at: string;
            /** Machine Id */
            machine_id: string;
            /** Tags */
            tags: {
                [key: string]: unknown;
            };
            certificate: components["schemas"]["CertificateSummary"] | null;
        };
        /** AgentPage */
        AgentPage: {
            /** Items */
            items: components["schemas"]["AgentSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AgentSummary */
        AgentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Hostname */
            hostname: string;
            /** Os */
            os: string;
            /** Os Version */
            os_version: string;
            /** Arch */
            arch: string;
            /** Agent Version */
            agent_version: string;
            /** Status */
            status: string;
            /** Group Id */
            group_id: string | null;
            /** Group Name */
            group_name: string | null;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Last Ip */
            last_ip: string | null;
            /** Clock Skew Ms */
            clock_skew_ms: number;
            /** Config Version */
            config_version: number;
            /**
             * Enrolled At
             * Format: date-time
             */
            enrolled_at: string;
        };
        /** ApiKeyResponse */
        ApiKeyResponse: {
            user: components["schemas"]["UserSummary"];
            /** Api Key */
            api_key: string;
        };
        /** AuditEntry */
        AuditEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seq */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** User Id */
            user_id: string | null;
            /** Username */
            username: string | null;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** AuditIntegrity */
        AuditIntegrity: {
            /** Intact */
            intact: boolean;
            /** Broken Seq */
            broken_seq: number | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEntry"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** BufferConfig */
        BufferConfig: {
            /**
             * Max Bytes
             * @default 524288000
             */
            max_bytes: number;
            /**
             * Max Age Days
             * @default 7
             */
            max_age_days: number;
        };
        /** CertificateSummary */
        CertificateSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Serial */
            serial: string;
            /** Fingerprint Sha256 */
            fingerprint_sha256: string;
            /**
             * Not Before
             * Format: date-time
             */
            not_before: string;
            /**
             * Not After
             * Format: date-time
             */
            not_after: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Revocation Reason */
            revocation_reason: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CommandCounts */
        CommandCounts: {
            /** Queued */
            queued: number;
            /** Failed 24H */
            failed_24h: number;
        };
        /** CommandPage */
        CommandPage: {
            /** Items */
            items: components["schemas"]["FleetCommand"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CommandResponse */
        CommandResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** CommandResultRequest */
        CommandResultRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "failed";
            /** Result */
            result?: {
                [key: string]: unknown;
            };
        };
        /**
         * CommandType
         * @enum {string}
         */
        CommandType: "ping" | "refresh_config" | "collect_diagnostics";
        /** ConfigResponse */
        ConfigResponse: {
            /** Scope */
            scope: string;
            /** Group Id */
            group_id: string | null;
            /** Document */
            document: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /** Updated At */
            updated_at: string | null;
        };
        /** ConfigUpdateRequest */
        ConfigUpdateRequest: {
            document: components["schemas"]["AgentConfigDocument"];
        };
        /** CreateCommandRequest */
        CreateCommandRequest: {
            type: components["schemas"]["CommandType"];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Ttl Seconds
             * @default 3600
             */
            ttl_seconds: number;
        };
        /** CreateEnrollmentTokenRequest */
        CreateEnrollmentTokenRequest: {
            /**
             * Max Uses
             * @default 1
             */
            max_uses: number;
            /** Ttl Hours */
            ttl_hours?: number | null;
            /** Group Id */
            group_id?: string | null;
        };
        /** CreateGroupRequest */
        CreateGroupRequest: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Username */
            username: string;
            /**
             * Role
             * @default operator
             * @enum {string}
             */
            role: "admin" | "operator";
            /** Scope Group Id */
            scope_group_id?: string | null;
        };
        /** EffectiveConfigResponse */
        EffectiveConfigResponse: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Document */
            document: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /** Applied Version */
            applied_version: number;
        };
        /** EnrollRequest */
        EnrollRequest: {
            /** Token */
            token: string;
            /** Csr Pem */
            csr_pem: string;
            host: components["schemas"]["HostFacts"];
        };
        /** EnrollResponse */
        EnrollResponse: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Certificate Pem */
            certificate_pem: string;
            /** Ca Pem */
            ca_pem: string;
            /** Config Version */
            config_version: number;
            /** Heartbeat Interval Seconds */
            heartbeat_interval_seconds: number;
        };
        /** EnrollmentTokenResponse */
        EnrollmentTokenResponse: {
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Max Uses */
            max_uses: number;
        };
        /** EnrollmentTokenSummary */
        EnrollmentTokenSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Group Id */
            group_id: string | null;
            /** Group Name */
            group_name: string | null;
            /** Created By */
            created_by: string | null;
            /** Created By Username */
            created_by_username: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Max Uses */
            max_uses: number;
            /** Used Count */
            used_count: number;
            /** Revoked At */
            revoked_at: string | null;
            /** State */
            state: string;
        };
        /** FleetCommand */
        FleetCommand: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Hostname */
            hostname: string;
        };
        /** FleetCounts */
        FleetCounts: {
            /** Total */
            total: number;
            /** Active */
            active: number;
            /** Offline */
            offline: number;
            /** Pending */
            pending: number;
            /** Quarantined */
            quarantined: number;
            /** Revoked */
            revoked: number;
        };
        /** GroupSummary */
        GroupSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Agent Count */
            agent_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatRequest */
        HeartbeatRequest: {
            /** Agent Version */
            agent_version: string;
            /** Config Version */
            config_version: number;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /**
             * Buffered Events
             * @default 0
             */
            buffered_events: number;
            /**
             * Buffer Bytes
             * @default 0
             */
            buffer_bytes: number;
        };
        /** HeartbeatResponse */
        HeartbeatResponse: {
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Config Version */
            config_version: number;
            /** Heartbeat Interval Seconds */
            heartbeat_interval_seconds: number;
            /** Commands */
            commands: components["schemas"]["QueuedCommand"][];
        };
        /** HostFacts */
        HostFacts: {
            /** Machine Id */
            machine_id: string;
            /** Hostname */
            hostname: string;
            /** Os */
            os: string;
            /** Os Version */
            os_version: string;
            /** Arch */
            arch: string;
            /** Agent Version */
            agent_version: string;
        };
        /** IssuedPasswordResponse */
        IssuedPasswordResponse: {
            user: components["schemas"]["UserSummary"];
            /** Password */
            password: string;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** LoggingConfig */
        LoggingConfig: {
            /**
             * Level
             * @default info
             * @enum {string}
             */
            level: "debug" | "info" | "warn" | "error";
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Overview */
        Overview: {
            agents: components["schemas"]["FleetCounts"];
            /** Certificates Expiring */
            certificates_expiring: number;
            /** Tokens Active */
            tokens_active: number;
            commands: components["schemas"]["CommandCounts"];
            /** Agent Versions */
            agent_versions: components["schemas"]["VersionCount"][];
            /** Operating Systems */
            operating_systems: components["schemas"]["VersionCount"][];
        };
        /** QueuedCommand */
        QueuedCommand: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RenewRequest */
        RenewRequest: {
            /** Csr Pem */
            csr_pem: string;
        };
        /** RenewResponse */
        RenewResponse: {
            /** Certificate Pem */
            certificate_pem: string;
            /** Ca Pem */
            ca_pem: string;
            /**
             * Not After
             * Format: date-time
             */
            not_after: string;
        };
        /** RevokeAgentRequest */
        RevokeAgentRequest: {
            /** Reason */
            reason: string;
        };
        /** SessionSummary */
        SessionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Ip */
            ip: string | null;
            /** User Agent */
            user_agent: string | null;
            /** Current */
            current: boolean;
        };
        /** SessionUser */
        SessionUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Scope Group Id */
            scope_group_id: string | null;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** TransportConfig */
        TransportConfig: {
            /**
             * Heartbeat Interval Seconds
             * @default 30
             */
            heartbeat_interval_seconds: number;
            /**
             * Event Batch Max
             * @default 500
             */
            event_batch_max: number;
            /**
             * Event Batch Max Bytes
             * @default 4194304
             */
            event_batch_max_bytes: number;
            /**
             * Backoff Base Seconds
             * @default 1
             */
            backoff_base_seconds: number;
            /**
             * Backoff Max Seconds
             * @default 300
             */
            backoff_max_seconds: number;
        };
        /** UpdateAgentRequest */
        UpdateAgentRequest: {
            /** Group Id */
            group_id?: string | null;
            /** Tags */
            tags?: {
                [key: string]: unknown;
            } | null;
        };
        /** UpdateGroupRequest */
        UpdateGroupRequest: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            /** Role */
            role?: ("admin" | "operator") | null;
            /** Scope Group Id */
            scope_group_id?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UserSummary */
        UserSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Scope Group Id */
            scope_group_id: string | null;
            /** Is Active */
            is_active: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /** Has Password */
            has_password: boolean;
            /** Has Api Key */
            has_api_key: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Locked Until */
            locked_until: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionCount */
        VersionCount: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_ca_certificate_gateway_v1_ca_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll_gateway_v1_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_gateway_v1_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    renew_gateway_v1_renew_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_config_gateway_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigResponse"];
                };
            };
        };
    };
    heartbeat_gateway_v1_heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_command_result_gateway_v1_commands__command_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                command_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    revoke_own_session_api_v1_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tokens_api_v1_enrollment_tokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenSummary"][];
                };
            };
        };
    };
    create_token_api_v1_enrollment_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnrollmentTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_token_api_v1_enrollment_tokens__token_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                group_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_certificates_api_v1_agents__agent_id__certificates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_agent_api_v1_agents__agent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_global_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    replace_global_config_api_v1_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_group_config_api_v1_groups__group_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_group_config_api_v1_groups__group_id__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_config_api_v1_groups__group_id__config_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_effective_agent_config_api_v1_agents__agent_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commands_api_v1_agents__agent_id__commands_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_command_api_v1_agents__agent_id__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_v1_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSummary"][];
                };
            };
        };
    };
    create_group_api_v1_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_v1_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_group_api_v1_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    create_console_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_console_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_api_key_api_v1_users__user_id__api_key_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    list_fleet_commands_api_v1_commands_get: {
        parameters: {
            query?: {
                status?: string | null;
                agent_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                action?: string | null;
                user_id?: string | null;
                since?: string | null;
                until?: string | null;
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditIntegrity"];
                };
            };
        };
    };
    read_audit_entry_api_v1_audit__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
