"""agent configs

Revision ID: b58749074118
Revises: 76cbd248f3b3
Create Date: 2026-09-14 23:37:59.854660
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b58749074118'
down_revision: str | None = '76cbd248f3b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'GROUP', name='config_scope', native_enum=False, length=32), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'GLOBAL' AND group_id IS NULL) OR (scope = 'GROUP' AND group_id IS NOT NULL)", name=op.f('ck_agent_configs_scope_group')),
    sa.ForeignKeyConstraint(['group_id'], ['agent_groups.id'], name=op.f('fk_agent_configs_group_id_agent_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_agent_configs_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_configs'))
    )
    op.create_index('uq_agent_configs_global', 'agent_configs', ['scope'], unique=True, postgresql_where=sa.text("scope = 'GLOBAL'"))
    op.create_index('uq_agent_configs_group', 'agent_configs', ['group_id'], unique=True, postgresql_where=sa.text("scope = 'GROUP'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_agent_configs_group', table_name='agent_configs', postgresql_where=sa.text("scope = 'GROUP'"))
    op.drop_index('uq_agent_configs_global', table_name='agent_configs', postgresql_where=sa.text("scope = 'GLOBAL'"))
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
