"""commands

Revision ID: dc0d578700db
Revises: b58749074118
Create Date: 2026-09-14 23:43:19.031666
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dc0d578700db'
down_revision: str | None = 'b58749074118'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PING', 'REFRESH_CONFIG', 'COLLECT_DIAGNOSTICS', name='command_type', native_enum=False, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'RUNNING', 'DONE', 'FAILED', 'EXPIRED', name='command_status', native_enum=False, length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_commands_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_commands_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commands'))
    )
    op.create_index(op.f('ix_commands_agent_id'), 'commands', ['agent_id'], unique=False)
    op.create_index('ix_commands_queued', 'commands', ['agent_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'QUEUED'"))
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index('ix_commands_queued', table_name='commands', postgresql_where=sa.text("status = 'QUEUED'"))
    op.drop_index(op.f('ix_commands_agent_id'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
