"""agent certificates

Revision ID: c440085f912f
Revises: 4bcb8d573b19
Create Date: 2026-09-11 16:36:24.206509
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c440085f912f'
down_revision: str | None = '4bcb8d573b19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_certificates_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['agent_certificates.id'], name=op.f('fk_agent_certificates_superseded_by_agent_certificates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_certificates'))
    )
    op.create_index(op.f('ix_agent_certificates_agent_id'), 'agent_certificates', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_certificates_fingerprint_sha256'), 'agent_certificates', ['fingerprint_sha256'], unique=False)
    op.create_index(op.f('ix_agent_certificates_serial'), 'agent_certificates', ['serial'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_certificates_serial'), table_name='agent_certificates')
    op.drop_index(op.f('ix_agent_certificates_fingerprint_sha256'), table_name='agent_certificates')
    op.drop_index(op.f('ix_agent_certificates_agent_id'), table_name='agent_certificates')
    op.drop_table('agent_certificates')
    # ### end Alembic commands ###
