"""console sessions and operator passwords

Revision ID: 3263ff47aa7a
Revises: bcae04c6f76a
Create Date: 2026-09-15 22:56:31.991755
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3263ff47aa7a'
down_revision: str | None = 'bcae04c6f76a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('console_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_console_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_console_sessions'))
    )
    op.create_index(op.f('ix_console_sessions_token_sha256'), 'console_sessions', ['token_sha256'], unique=True)
    op.create_index(op.f('ix_console_sessions_user_id'), 'console_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'api_key_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###

    # Область видимости оператора держалась на ON DELETE SET NULL: удаление
    # группы обнуляло scope_group_id, и офицер филиала незаметно получал весь
    # флот. Связь становится RESTRICT — удалить группу можно только отвязав
    # от неё операторов.
    op.drop_constraint(
        op.f('fk_users_scope_group_id_agent_groups'), 'users', type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('fk_users_scope_group_id_agent_groups'),
        'users',
        'agent_groups',
        ['scope_group_id'],
        ['id'],
        ondelete='RESTRICT',
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f('fk_users_scope_group_id_agent_groups'), 'users', type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('fk_users_scope_group_id_agent_groups'),
        'users',
        'agent_groups',
        ['scope_group_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_attempts')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_console_sessions_user_id'), table_name='console_sessions')
    op.drop_index(op.f('ix_console_sessions_token_sha256'), table_name='console_sessions')
    op.drop_table('console_sessions')
    # ### end Alembic commands ###
