"""agents and groups

Revision ID: b18cf658a324
Revises: 28e6d06930c4
Create Date: 2026-09-11 16:33:19.872972
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b18cf658a324'
down_revision: str | None = '28e6d06930c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['agent_groups.id'], name=op.f('fk_agent_groups_parent_id_agent_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_groups'))
    )
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=32), nullable=False),
    sa.Column('os_version', sa.String(length=128), nullable=False),
    sa.Column('arch', sa.String(length=32), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'OFFLINE', 'QUARANTINED', 'REVOKED', name='agent_status', native_enum=False, length=32), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_skew_ms', sa.BigInteger(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('last_ip', postgresql.INET(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['agent_groups.id'], name=op.f('fk_agents_group_id_agent_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_group_id'), 'agents', ['group_id'], unique=False)
    op.create_index(op.f('ix_agents_last_heartbeat_at'), 'agents', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_agents_machine_id'), 'agents', ['machine_id'], unique=True)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_machine_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_last_heartbeat_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_group_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('agent_groups')
    # ### end Alembic commands ###
