"""enrollment tokens

Revision ID: 4bcb8d573b19
Revises: b18cf658a324
Create Date: 2026-09-11 16:34:07.213970
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4bcb8d573b19'
down_revision: str | None = 'b18cf658a324'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['agent_groups.id'], name=op.f('fk_enrollment_tokens_group_id_agent_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_tokens'))
    )
    op.create_index(op.f('ix_enrollment_tokens_token_sha256'), 'enrollment_tokens', ['token_sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_tokens_token_sha256'), table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    # ### end Alembic commands ###
