"""users

Revision ID: 76cbd248f3b3
Revises: 24aa2816b5e0
Create Date: 2026-09-11 16:40:46.107496
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '76cbd248f3b3'
down_revision: str | None = '24aa2816b5e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('api_key_sha256', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('scope_group_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scope_group_id'], ['agent_groups.id'], name=op.f('fk_users_scope_group_id_agent_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_api_key_sha256'), 'users', ['api_key_sha256'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_api_key_sha256'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
